### ISSUE TITLE
Error Compiling: 'SPISettings()' was not declared in this scope

### ISSUE THREAD

**Issue by tbitson** [sparkfun/SparkFun_AS3935_Lightning_Detector_Arduino_Library#11]
Complier can't find the function "SPISettings(_spiPortSpeed, MSBFIRST, SPI_MODE1)" in line 468:  _spiPort->beginTransaction(SPISettings(_spiPortSpeed, MSBFIRST, SPI_MODE1));
Same issue on line 491. 

I searched to code and example, couldn't find the function. Is it in one of the libraries?

**Comment by edspark** [comment]
I'll need a little more information. Are you using Arduino, and with what micro-controller? If you wouldn't mind also linking your code, or is it just the example code?

**Comment by edspark** [comment]
Hello, I'm going to close this out for now. Please reopen it if you're still having some issues!
